package io.dargent.pspsimulator.charge;

import java.time.Instant;

import io.dargent.pspsimulator.error.PspApiException;

/**
 * A cob (charge) as the PSP owns it (E2 spec §5.1–§5.3). The merchant's txid is the key; amount is
 * integer cents; expiry is PSP truth. Pure Java — no framework imports.
 *
 * <p>Transition rules (evaluation order per spec §5.3): paying an already-paid charge →
 * {@code 409 already_paid}; paying an OPEN charge after {@code expiresAt} → {@code 409 charge_expired};
 * otherwise the charge becomes PAID, irreversibly, stamped with the payer bank's ids.
 */
public final class Charge {

    private final String txid;
    private final long amount;
    private final Instant expiresAt;
    private final String callbackUrl;
    private final String description;

    private ChargeStatus status = ChargeStatus.OPEN;
    private String endToEndId;
    private String eventId;
    private Instant paidAt;

    public Charge(String txid, long amount, Instant expiresAt, String callbackUrl, String description) {
        this.txid = txid;
        this.amount = amount;
        this.expiresAt = expiresAt;
        this.callbackUrl = callbackUrl;
        this.description = description;
    }

    /**
     * Status as of {@code now}: EXPIRED is derived from expiry for unpaid charges; PAID is permanent.
     */
    public ChargeStatus statusFor(Instant now) {
        if (status == ChargeStatus.PAID) {
            return ChargeStatus.PAID;
        }
        return now.isAfter(expiresAt) ? ChargeStatus.EXPIRED : ChargeStatus.OPEN;
    }

    /**
     * The payer bank pays this charge. {@code endToEndId}/{@code eventId} are generated by the caller
     * and stamped here — the eventId stays stable so the duplicate chaos knob can re-deliver it.
     */
    public void pay(Instant now, String endToEndId, String eventId) {
        if (status == ChargeStatus.PAID) {
            throw new PspApiException(409, "already_paid", "Charge " + txid + " is already paid");
        }
        if (now.isAfter(expiresAt)) {
            throw new PspApiException(409, "charge_expired", "Charge " + txid + " expired at " + expiresAt);
        }
        this.status = ChargeStatus.PAID;
        this.endToEndId = endToEndId;
        this.eventId = eventId;
        this.paidAt = now;
    }

    public String txid() {
        return txid;
    }

    public long amount() {
        return amount;
    }

    public Instant expiresAt() {
        return expiresAt;
    }

    public String callbackUrl() {
        return callbackUrl;
    }

    public String description() {
        return description;
    }

    /** Stored status (never EXPIRED — that is derived via {@link #statusFor(Instant)}). */
    public ChargeStatus status() {
        return status;
    }

    public String endToEndId() {
        return endToEndId;
    }

    public String eventId() {
        return eventId;
    }

    public Instant paidAt() {
        return paidAt;
    }
}